### ISSUE TITLE
WMS tjenester fra Plandata.dk - fejler

### ISSUE THREAD

**Issue by GISAabenraa** [danmarksmiljoeportal/datacatalog-qgis-plugin#2]
De fleste WMS-tjenester fra plandata i DMP-catalogue fejler med  "DMP Catalogue: Failed to load layer: 
WMS provider: Cannot calculate extent"

**Comment by strandbygaard** [comment]
Tak fordi i gør opmærksom på det. 

Vi kan ikke umiddelbart løse problemet i selve QGIS plugin. Fejlen opstår når QGIS forsøger at hente laget fra geoserveren hos plandata. Efter at laget er tilføjet QGIS vha. plugin.

GDAL kan heller ikke loadet laget fra geoserveren. GDAL giver lidt mere tekniske fejl om problemet: 
Unsupported conversion method: Lambert Conic Near-Conformal
Unsupported conversion method: Lambert Conic Conformal (West Orientated)
Unsupported conversion method: Bonne (South Orientated)
Unsupported conversion method: Polar Stereographic (variant C)
